"""Schema constants for Package 1 synthetic source tables."""

from __future__ import annotations

SOURCE_TABLES: tuple[str, ...] = (
    "accounts",
    "users",
    "usage_events",
    "subscriptions",
    "invoices",
    "support_tickets",
    "crm_touchpoints",
    "renewals",
)

REQUIRED_COLUMNS: dict[str, tuple[str, ...]] = {
    "accounts": (
        "account_id",
        "account_name",
        "created_date",
        "industry",
        "region",
        "segment",
        "company_size_band",
        "acquisition_channel",
        "initial_plan",
        "synthetic_archetype",
    ),
    "users": (
        "user_id",
        "account_id",
        "created_date",
        "role_type",
        "is_admin",
    ),
    "usage_events": (
        "event_id",
        "account_id",
        "user_id",
        "event_timestamp",
        "event_type",
        "event_value",
    ),
    "subscriptions": (
        "subscription_id",
        "account_id",
        "plan",
        "start_date",
        "end_date",
        "mrr",
        "billing_period",
        "status",
    ),
    "invoices": (
        "invoice_id",
        "account_id",
        "invoice_date",
        "due_date",
        "paid_date",
        "amount",
        "status",
    ),
    "support_tickets": (
        "ticket_id",
        "account_id",
        "created_at",
        "resolved_at",
        "priority",
        "category",
        "status",
        "csat_score",
    ),
    "crm_touchpoints": (
        "touchpoint_id",
        "account_id",
        "touchpoint_date",
        "team",
        "touchpoint_type",
        "outcome",
    ),
    "renewals": (
        "renewal_id",
        "account_id",
        "renewal_date",
        "outcome",
        "previous_mrr",
        "new_mrr",
    ),
}

PRIMARY_KEYS: dict[str, str] = {
    "accounts": "account_id",
    "users": "user_id",
    "usage_events": "event_id",
    "subscriptions": "subscription_id",
    "invoices": "invoice_id",
    "support_tickets": "ticket_id",
    "crm_touchpoints": "touchpoint_id",
    "renewals": "renewal_id",
}

FOREIGN_KEYS: dict[str, dict[str, tuple[str, str]]] = {
    "users": {"account_id": ("accounts", "account_id")},
    "usage_events": {
        "account_id": ("accounts", "account_id"),
        "user_id": ("users", "user_id"),
    },
    "subscriptions": {"account_id": ("accounts", "account_id")},
    "invoices": {"account_id": ("accounts", "account_id")},
    "support_tickets": {"account_id": ("accounts", "account_id")},
    "crm_touchpoints": {"account_id": ("accounts", "account_id")},
    "renewals": {"account_id": ("accounts", "account_id")},
}

ALLOWED_VALUES: dict[str, tuple[str, ...]] = {
    "industry": (
        "software",
        "financial_services",
        "healthcare",
        "education",
        "retail",
        "manufacturing",
        "professional_services",
        "media",
    ),
    "region": ("north_america", "europe", "asia_pacific", "latin_america"),
    "segment": ("smb", "mid_market", "enterprise"),
    "company_size_band": ("1_50", "51_200", "201_1000", "1001_5000", "5001_plus"),
    "acquisition_channel": (
        "inbound",
        "partner",
        "outbound",
        "product_led",
        "event",
    ),
    "plan": ("starter", "growth", "business", "enterprise"),
    "synthetic_archetype": (
        "healthy_growing",
        "steady_retained",
        "low_adoption",
        "support_frustrated",
        "seasonal",
        "expansion_ready",
        "price_sensitive",
        "implementation_risk",
    ),
    "role_type": ("admin", "manager", "contributor", "viewer", "analyst", "developer"),
    "event_type": (
        "login",
        "dashboard_view",
        "report_export",
        "workflow_run",
        "integration_sync",
        "api_call",
        "seat_invited",
    ),
    "billing_period": ("monthly", "annual"),
    "subscription_status": ("active", "ended", "cancelled"),
    "invoice_status": ("paid", "open", "failed", "void"),
    "ticket_priority": ("low", "medium", "high", "urgent"),
    "ticket_category": (
        "billing",
        "bug",
        "how_to",
        "integration",
        "performance",
        "implementation",
    ),
    "ticket_status": ("open", "resolved", "closed"),
    "touchpoint_team": ("sales", "customer_success", "support", "growth"),
    "touchpoint_type": (
        "onboarding",
        "business_review",
        "renewal_check_in",
        "expansion_discussion",
        "risk_review",
        "training",
    ),
    "touchpoint_outcome": (
        "completed",
        "no_show",
        "follow_up_needed",
        "opportunity_created",
        "risk_identified",
        "resolved",
    ),
    "renewal_outcome": (
        "renewed_flat",
        "renewed_expanded",
        "renewed_contracted",
        "churned",
    ),
}
