"""Candidate model training contracts for Package 5."""

from account_health.modeling.dataset import (
    APPROVED_CATEGORICAL_FEATURES,
    APPROVED_NUMERIC_FEATURES,
    DEFAULT_MODELING_FEATURE_SET,
    FORBIDDEN_FEATURE_NAME_TERMS,
    FORBIDDEN_MODELING_FEATURES,
    GRAIN_COLUMNS,
    MODELING_SOURCE_TABLE,
    TARGET_COLUMNS,
    ModelingDataset,
    ModelingDatasetError,
    ModelingFeatureSet,
    load_modeling_dataset,
    validate_modeling_feature_set,
    validate_modeling_source_columns,
)
from account_health.modeling.candidates import (
    LOGISTIC_REGRESSION,
    RANDOM_FOREST,
    REQUIRED_METRIC_KEYS,
    SUPPORTED_CANDIDATE_MODELS,
    CandidateTrainingResult,
    ModelingCandidateError,
    build_candidate_pipeline,
    evaluate_binary_metrics,
    train_candidate_model,
)
from account_health.modeling.split import (
    ModelingSplitError,
    TemporalSplit,
    split_modeling_dataset,
)
from account_health.modeling.training import (
    DEFAULT_EXPERIMENT_NAME,
    CandidateRunSummary,
    CandidateTrainingOrchestrationResult,
    ModelingTrainingError,
    train_candidate_models,
)

__all__ = [
    "APPROVED_CATEGORICAL_FEATURES",
    "APPROVED_NUMERIC_FEATURES",
    "DEFAULT_MODELING_FEATURE_SET",
    "DEFAULT_EXPERIMENT_NAME",
    "FORBIDDEN_FEATURE_NAME_TERMS",
    "FORBIDDEN_MODELING_FEATURES",
    "GRAIN_COLUMNS",
    "MODELING_SOURCE_TABLE",
    "LOGISTIC_REGRESSION",
    "RANDOM_FOREST",
    "REQUIRED_METRIC_KEYS",
    "SUPPORTED_CANDIDATE_MODELS",
    "TARGET_COLUMNS",
    "CandidateTrainingResult",
    "CandidateRunSummary",
    "CandidateTrainingOrchestrationResult",
    "ModelingDataset",
    "ModelingDatasetError",
    "ModelingFeatureSet",
    "ModelingCandidateError",
    "ModelingSplitError",
    "ModelingTrainingError",
    "TemporalSplit",
    "build_candidate_pipeline",
    "evaluate_binary_metrics",
    "load_modeling_dataset",
    "split_modeling_dataset",
    "train_candidate_model",
    "train_candidate_models",
    "validate_modeling_feature_set",
    "validate_modeling_source_columns",
]
